<a href="https://colab.research.google.com/github/fleshgordo/cocreate22/blob/main/sandbox/099_sandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Some xeno-canto queries:

Look for specific user:
```
https://xeno-canto.org/api/2/recordings?query=rec%3A%22VORNAME%20NACHNAME%22
```

Look for links in the remarks area:
```
https://xeno-canto.org/api/2/recordings?query=rmk:https
```

# Export results from xeno-canto as geo-coordinates to CSV files

This will export all the results from given query into a CSV file with the column tables: "lat", "lng" and "rmk" (position latitude, longitude and comment of a recording). See the file ```sample_output/output.csv``` after running this code.

In [ ]:
import requests
import pandas as pd

params = "cnt:switzerland loc:basel"
url="https://www.xeno-canto.org/api/2/recordings?query="+params
print(url)
r = requests.get(url, headers={"Content-Type":"json"})
resp = r.json()

df = pd.DataFrame.from_dict(resp["recordings"])
outputfile = './sample_data/output.csv'
df.dropna().to_csv(outputfile, columns = ["lat","lng","rmk"])

https://www.xeno-canto.org/api/2/recordings?query=cnt:switzerland loc:basel

# Quick xeno-canto query to pandas

If you receive more than 500 results on a query, you can concatenate some of the requests in a big pandas dataframe by manually changing the page number.

In [ ]:
import requests
import pandas as pd

# making the request
params = "cnt:germany&page=5" # change page=1, page=2, page=3 etc. if there are more than 500results
url="https://www.xeno-canto.org/api/2/recordings?query="+params
r = requests.get(url, headers={"Content-Type":"json"})
resp = r.json()
#print(resp)

# creating a new dataframe in case there's none, otherwise concatening existing one
if df is None:
  print("first runtime ... creating dataframe")
  df = pd.DataFrame.from_dict(resp["recordings"])
else:
  df = pd.concat([df, pd.DataFrame.from_dict(resp["recordings"])])
  print("adding " + str(len(resp["recordings"])) + " entries to existing dataframe")
  print("currently " + str(len(df.index)) + " entries in dataframe")

adding 500 entries to existing dataframe
currently 4000 entries in dataframe

In [ ]:
df

,id,gen,sp,ssp,en,rec,cnt,loc,lat,lng,...,lic,q,length,time,date,uploaded,also,rmk,bird-seen,playback-used
0,127145,Rhea,americana,,Greater Rhea,Lars Lachmann,Germany,east of Ratzeburger See,53.7688,10.7742,...,//creativecommons.org/licenses/by-nc-sa/3.0/,B,0:03,14:29,2013-02-16,2013-03-24,[],snorting sound given during aggressin between ...,unknown,unknown
1,127143,Rhea,americana,,Greater Rhea,Lars Lachmann,Germany,east of Ratzeburger See,53.7688,10.7742,...,//creativecommons.org/licenses/by-nc-sa/3.0/,D,0:02,14:26,2013-02-16,2013-03-24,[],booming song of a male bird. There is now a fe...,yes,no
2,133402,Tetrastes,bonasia,,Hazel Grouse,Matthias Feuersenger,Germany,"Near Stellwand, Oberammergau, Upper Bavaria, B...",47.5397,10.9783,...,//creativecommons.org/licenses/by-nc-sa/3.0/,A,0:25,08:40,2013-05-03,2013-05-12,[],Bird singing from the ground in moist young mi...,yes,no
3,437461,Tetrastes,bonasia,,Hazel Grouse,Julia Wittmann,Germany,"Finsterauer Filz, Freyung-Grafenau (near Maut...",48.9492,13.5775,...,//creativecommons.org/licenses/by-nc-sa/4.0/,B,0:20,06:35,2018-09-30,2018-10-06,"[Turdus philomelos, Prunella modularis, Fringi...",,yes,no
4,437459,Tetrastes,bonasia,,Hazel Grouse,Julia Wittmann,Germany,"Finsterauer Filz, Freyung-Grafenau (near Maut...",48.9492,13.5775,...,//creativecommons.org/licenses/by-nc-sa/4.0/,B,0:19,06:35,2018-09-30,2018-10-06,"[Turdus merula, Turdus philomelos]",,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,479633,Scolopax,rusticola,,Eurasian Woodcock,Frank Holzapfel,Germany,"Naturpark Stromberg-Heuchelberg, Baden-Württem...",48.9785,8.9145,...,//creativecommons.org/licenses/by-nc-nd/4.0/,C,0:40,21:10,2019-05-01,2019-06-08,[],"Cut 3 of 17: Woodcock's high pitched ""pist"" e...",yes,no
496,479631,Scolopax,rusticola,,Eurasian Woodcock,Frank Holzapfel,Germany,"Naturpark Stromberg-Heuchelberg, Baden-Württem...",48.9785,8.9145,...,//creativecommons.org/licenses/by-nc-nd/4.0/,C,0:36,20:52,2019-05-01,2019-06-08,[],Cut 1 of 17: The Woodcock songster shows up 12...,yes,no
497,478431,Scolopax,rusticola,,Eurasian Woodcock,Stephan Risch,Germany,"Solingen, Düsseldorf, Nordrhein-Westfalen",51.1572,6.9713,...,//creativecommons.org/licenses/by-nc-sa/4.0/,C,0:02,21:52,2016-06-18,2019-06-02,[],Three Calls automatically recorded (Pettersson...,no,no
498,288943,Scolopax,rusticola,,Eurasian Woodcock,Nils Agster,Germany,"Tübingen (near Rottenburg am Neckar), Tübinge...",48.4213,8.9489,...,//creativecommons.org/licenses/by-nc-sa/4.0/,C,0:12,22:00,2015-06-03,2015-11-07,[],,yes,no
499,665617,Scolopax,rusticola,,Eurasian Woodcock,Frank Holzapfel,Germany,"Naturpark Stromberg-Heuchelberg, Baden-Württem...",49.0063,8.9053,...,//creativecommons.org/licenses/by-nc-nd/4.0/,D,0:20,21:37,2021-06-02,2021-07-30,[],Roding area of Eurasian Woodcock *Scolopax rus...,yes,no

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

# Extract all links from results

Looks for links with the search term ```https``` and makes a query (```https://xeno-canto.org/api/2/recordings?query=rmk%3A%22https%22```). Later on, extracting the URLs from the remark section and store them in a list.

In [ ]:

import requests
import pandas as pd
import re

#params = "rmk:https cnt:Switzerland loc:Basel"
params = "rmk:https cnt:Brazil"
#params = "rmk:youtube cnt:Germany" 

url="https://www.xeno-canto.org/api/2/recordings?query="+params

r = requests.get(url, headers={"Content-Type":"json"})
resp = r.json()

print("there are " + str(len(resp["recordings"])) + " recordings with links in the remark section")
comments = resp["recordings"]

there are 156 recordings with links in the remark section

For extracting all hyperlinks in the comments we need a regular expression and to extract within each remark the link that starts with https:// ...

In [ ]:
urls = []
for comment in comments:
    regularex = r'(https:[\'"]?[^\'"\) >]+)'
    url = re.findall(regularex, comment["rmk"])
    urls.extend(url)
    print(url)
print("could extract " + str(len(urls)) + " hyperlinks")

## Pivottable

For quick exploration of a dataframe [pivottablejs](https://pivottable.js.org/) is quite useful. Install it via pip:

In [1]:
# install 
!pip install pivottablejs

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pivottablejs
  Downloading pivottablejs-0.9.0-py2.py3-none-any.whl (4.7 kB)
Installing collected packages: pivottablejs
Successfully installed pivottablejs-0.9.0

In [3]:
# create a df from download
import requests
import pandas as pd
all_animals = requests.get("https://github.com/fleshgordo/cocreate22/raw/main/sample_data/20220917-181514-api-all-animals.json")
all_animals = all_animals.json()
df = pd.json_normalize(all_animals["data"])
df

,id,type,attributes.id,attributes.alive,attributes.ring_id,attributes.distance_24h_m,attributes.name,attributes.is_highlighted,attributes.content_url,attributes.image_url,attributes.last_location.latitude,attributes.last_location.longitude,attributes.last_location.timestamp,relationships.specie.data.id,relationships.specie.data.type
0,7e9f780e-0acb-4e9c-a813-1c30b1cd0e68,animal,7e9f780e-0acb-4e9c-a813-1c30b1cd0e68,True,,NaN,02a9,False,https://animaltracker.app/api/v1/animals/7e9f7...,None,24.431216,32.757590,2022-08-27T16:01:26.000+02:00,b3eeb878-4aa2-4a2e-aaa7-c4929a6d9266,specie
1,4ff7d460-f936-49a4-a00d-56c208e44641,animal,4ff7d460-f936-49a4-a00d-56c208e44641,True,0679-01594,NaN,Charlie,False,https://animaltracker.app/api/v1/animals/4ff7d...,None,46.555000,-112.861700,2022-04-11T01:00:11.000+02:00,82c04a5e-162d-4054-9ea1-dac19545d5a0,specie
2,24cc5ea8-dcc4-419d-9f90-f5a668c14895,animal,24cc5ea8-dcc4-419d-9f90-f5a668c14895,True,0679-01596,NaN,Pilot,False,https://animaltracker.app/api/v1/animals/24cc5...,None,47.226100,-113.310800,2022-09-08T01:00:33.000+02:00,82c04a5e-162d-4054-9ea1-dac19545d5a0,specie
3,48c7a06e-f5f3-4133-b04e-c7980d3e35d1,animal,48c7a06e-f5f3-4133-b04e-c7980d3e35d1,True,0709-01883,NaN,Wanderer,False,https://animaltracker.app/api/v1/animals/48c7a...,None,46.206170,-113.894830,2022-08-11T23:00:00.000+02:00,82c04a5e-162d-4054-9ea1-dac19545d5a0,specie
4,a97c7725-cd9a-4840-a942-5f52d4a12d4a,animal,a97c7725-cd9a-4840-a942-5f52d4a12d4a,True,0709-02458,NaN,Taku,False,https://animaltracker.app/api/v1/animals/a97c7...,None,58.567170,-131.969170,2022-09-16T03:00:00.000+02:00,82c04a5e-162d-4054-9ea1-dac19545d5a0,specie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5065,c2aa97ab-f4f7-4f4e-bc21-689f4f6eea9e,animal,c2aa97ab-f4f7-4f4e-bc21-689f4f6eea9e,True,,41.0,ZOO w-wa,False,https://animaltracker.app/api/v1/animals/c2aa9...,None,40.019037,30.030342,2022-09-16T20:58:16.000+02:00,b3eeb878-4aa2-4a2e-aaa7-c4929a6d9266,specie
5066,07a57a88-2f46-4aaf-a4cc-06d90d4f2188,animal,07a57a88-2f46-4aaf-a4cc-06d90d4f2188,True,164,6585.0,Zoppo,False,https://animaltracker.app/api/v1/animals/07a57...,None,47.790104,9.287352,2022-09-17T16:50:15.000+02:00,66520f65-b48d-4ef7-b65b-7efec70f061d,specie
5067,45c8f98d-a209-46d3-b330-b9aadd9eb02c,animal,45c8f98d-a209-46d3-b330-b9aadd9eb02c,True,,NaN,Unnamed,False,https://animaltracker.app/api/v1/animals/45c8f...,None,35.063362,-77.088932,2015-05-15T21:01:11.000+02:00,ce105134-d90e-47dd-a75f-4d2c28cd3e64,specie
5068,96a0014e-c310-4b32-9813-78690dbf5154,animal,96a0014e-c310-4b32-9813-78690dbf5154,True,,NaN,Unnamed,False,https://animaltracker.app/api/v1/animals/96a00...,None,34.844276,-76.419373,2022-05-15T14:10:03.000+02:00,51515a23-0dce-4c34-b6e0-1179b36575a5,specie
5069,c1cff0e4-e184-43d3-bc55-4cf97ffd0c1b,animal,c1cff0e4-e184-43d3-bc55-4cf97ffd0c1b,True,,NaN,TowerJunct_F,False,https://animaltracker.app/api/v1/animals/c1cff...,None,44.909236,-110.420282,2021-12-11T19:00:11.000+01:00,840ca53f-c3b0-4458-91a6-728a0e208479,specie

In [ ]:
# create the pivottable
from pivottablejs import pivot_ui # import pivottable
pivot_ui(df,outfile_path="sample_data/pivottablejs.html") # will save the html to folder

This will create pivottablejs.html in the sample_data folder. Remember without pivottable your code might look like this [link text](https://miro.medium.com/max/1272/1*kuIcMlTi8VzVCZXm47I8hQ.png)